version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    ports:
      - "5002:5002"
    networks:
      - mynetwork

  nginx_front:
    build: ./nginx_front
    container_name: nginx_front
    restart: always
    ports:
      - "81:81"
    networks:
      - mynetwork
      
  nginx_backend:
    build: ./nginx_backend
    container_name: nginx_backend
    restart: always
    ports:
      - "82:82"
    networks:
      - mynetwork

networks:
    mynetwork:
        driver: "bridge"

